game_info:
  table_name: "game_info"
  create_table_file: "./queries/create_game_info.sql"
  insert_file: "./queries/insert_game_info.sql"
  insert_get_id_file: "./queries/insert_get_id_game_info.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"
  select_game_id_file: "./queries/select_id_game_info.sql"
  select_file: "./queries/select_all.sql"
  update_path_file: "./queries/update_path_game_info.sql"
    
player_info:  
  table_name: "player_info"
  create_table_file: "./queries/create_player_info.sql"
  insert_file: "./queries/insert_player_info.sql"
  update_file: "./queries/update_player_info.sql"
  preinsert_select_file: "./queries/preinsert_select_player_info.sql"
  select_file: "./queries/select_all.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

map_info:
  table_name: "map_info"
  create_table_file: "./queries/create_map_info.sql"
  insert_file: "./queries/insert_map_info.sql"
  update_file: "./queries/update_map_info.sql"
  preinsert_select_file: "./queries/preinsert_select_map_info.sql"
  select_file: "./queries/select_all.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

build_order:
  table_name: "build_order"
  create_table_file: "./queries/create_build_order.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_build_order.sql"
  select_file: "./queries/select_all.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

zvt_comp:
  table_name: "zvt_comp"
  create_table_file: "./queries/create_zvt_comp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvt_comp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvp_comp:
  table_name: "zvp_comp"
  create_table_file: "./queries/create_zvp_comp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvp_comp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvz_comp:
  table_name: "zvz_comp"
  create_table_file: "./queries/create_zvz_comp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvz_comp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"

zvt_winprob:
  table_name: "zvt_comp"
  create_table_file: "./queries/create_zvt_winprob.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvt_winprob.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvp_winprob:
  table_name: "zvp_comp"
  create_table_file: "./queries/create_zvp_winprob.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvp_winprob.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvz_winprob:
  table_name: "zvz_comp"
  create_table_file: "./queries/create_zvz_winprob.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvz_winprob.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"

zvt_enemycomp:
  table_name: "zvt_comp"
  create_table_file: "./queries/create_zvt_enemycomp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvt_enemycomp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvp_enemycomp:
  table_name: "zvp_comp"
  create_table_file: "./queries/create_zvp_enemycomp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvp_enemycomp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
zvz_enemycomp:
  table_name: "zvz_comp"
  create_table_file: "./queries/create_zvz_enemycomp.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_zvz_enemycomp.sql"
  select_file: "./queries/select_all.sql"
  drop_table_file: "./queries/drop_table.sql"
