game_info:
  table_name: "game_info"
  columns:
    game_id: "INTEGER SERIAL PRIMARY KEY"
    timestamp_played: "TIMESTAMP NOT NULL"
    timestamp_processed: "TIMESTAMP"
    players_hash: "VARCHAR(64) NOT NULL"
    end_time: "INTEGER (CHECK end_time > 0)"
    player_1_id: "VARCHAR(12) NOT NULL"
    player_1_race: "VARCHAR(1) NOT NULL"
    player_1_league: "INTEGER"
    player_2: "VARCHAR(12) NOT NULL"
    player_2_race: "VARCHAR(1) NOT NULL"
    player_2_league: "INTEGER"
    map_hash: "VARCHAR(50) NOT NULL"
    matchup: "VARCHAR(5) NOT NULL"
    is_ladder: "BOOLEAN"
    replay_path: "VARCHAR(250)"
  creation_closure: 
    row0: "FOREIGN KEY (player_1_id) REFERENCES player_info(id)"
    row1: "FOREIGN KEY (player_1_id) REFERENCES player_info(id)"
    row2: "FOREIGN KEY (map_hash) REFERENCES map_info(map_hash)"
    
player_info:  
  table_name: "player_info"
  columns:
    id: "INTEGER PRIMARY KEY"
    nickname: "VARCHAR(12)"
    games_played: "INTEGER"
    zerg_played: "INTEGER"
    protoss_played: "INTEGER"
    terran_played: "INTEGER"
    wins: "INTEGER"
    loses: "INTEGER"
    most_played_race: "VARCHAR(1)"
    highest_league: "INTEGER"

map_info:
  table_name: "map_info"
  columns:
    map_hash: "VARCHAR(50) PRIMARY KEY"
    map_name: "VARCHAR(50)"
    matchup_type: "VARCHAR(10)"
    first_game_date: "DATE"

build_order:
  table_name: "build_order"
  columns:
    tick: "INTEGER (CHECK tick > 0)"
    game_id: "VARCHAR(50)"
    player_1_upgrade_AnabolicSynthesis: 'INTEGER'
    player_1_upgrade_Burrow: 'INTEGER'
    player_1_upgrade_CentrificalHooks: 'INTEGER'
    player_1_upgrade_ChitinousPlating: 'INTEGER'
    player_1_upgrade_DiggingClaws: 'INTEGER'
    player_1_upgrade_EvolveGroovedSpines: 'INTEGER'
    player_1_upgrade_EvolveMuscularAugments: 'INTEGER'
    player_1_upgrade_GlialReconstitution: 'INTEGER'
    player_1_upgrade_InfestorEnergyUpgrade: 'INTEGER'
    player_1_upgrade_LurkerRange: 'INTEGER'
    player_1_upgrade_NeuralParasite: 'INTEGER'
    player_1_upgrade_overlordspeed: 'INTEGER'
    player_1_upgrade_TunnelingClaws: 'INTEGER'
    player_1_upgrade_ZergFlyerArmorsLevel1: 'INTEGER'
    player_1_upgrade_ZergFlyerArmorsLevel2: 'INTEGER'
    player_1_upgrade_ZergFlyerArmorsLevel3: 'INTEGER'
    player_1_upgrade_ZergFlyerWeaponsLevel1: 'INTEGER'
    player_1_upgrade_ZergFlyerWeaponsLevel2: 'INTEGER'
    player_1_upgrade_ZergFlyerWeaponsLevel3: 'INTEGER'
    player_1_upgrade_ZergGroundArmorsLevel1: 'INTEGER'
    player_1_upgrade_ZergGroundArmorsLevel2: 'INTEGER'
    player_1_upgrade_ZergGroundArmorsLevel3: 'INTEGER'
    player_1_upgrade_zerglingattackspeed: 'INTEGER'
    player_1_upgrade_zerglingmovementspeed: 'INTEGER'
    player_1_upgrade_ZergMeleeWeaponsLevel1: 'INTEGER'
    player_1_upgrade_ZergMeleeWeaponsLevel2: 'INTEGER'
    player_1_upgrade_ZergMeleeWeaponsLevel3: 'INTEGER'
    player_1_upgrade_ZergMissileWeaponsLevel1: 'INTEGER'
    player_1_upgrade_ZergMissileWeaponsLevel2: 'INTEGER'
    player_1_upgrade_ZergMissileWeaponsLevel3: 'INTEGER'
    player_1_unit_Drone: 'INTEGER'
    player_1_unit_Queen: 'INTEGER'
    player_1_unit_Zergling: 'INTEGER'
    player_1_unit_Baneling: 'INTEGER'
    player_1_unit_Roach: 'INTEGER'
    player_1_unit_Ravager: 'INTEGER'
    player_1_unit_Hydralisk: 'INTEGER'
    player_1_unit_Lurker: 'INTEGER'
    player_1_unit_Infestor: 'INTEGER'
    player_1_unit_SwarmHost: 'INTEGER'
    player_1_unit_Ultralisk: 'INTEGER'
    player_1_unit_Overlord: 'INTEGER'
    player_1_unit_Overseer: 'INTEGER'
    player_1_unit_Mutalisk: 'INTEGER'
    player_1_unit_Corruptor: 'INTEGER'
    player_1_unit_Viper: 'INTEGER'
    player_1_unit_BroodLord: 'INTEGER'
    player_1_unit_Hatchery: 'INTEGER'
    player_1_unit_Extractor: 'INTEGER'
    player_1_unit_SpawningPool: 'INTEGER'
    player_1_unit_EvolutionChamber: 'INTEGER'
    player_1_unit_SpineCrawler: 'INTEGER'
    player_1_unit_SporeCrawler: 'INTEGER'
    player_1_unit_RoachWarren: 'INTEGER'
    player_1_unit_BanelingNest: 'INTEGER'
    player_1_unit_Lair: 'INTEGER'
    player_1_unit_HydraliskDen: 'INTEGER'
    player_1_unit_LurkerDen: 'INTEGER'
    player_1_unit_InfestationPit: 'INTEGER'
    player_1_unit_Spire: 'INTEGER'
    player_1_unit_NydusNetwork: 'INTEGER'
    player_1_unit_Hive: 'INTEGER'
    player_1_unit_UltraliskCavern: 'INTEGER'
    player_1_unit_GreaterSpire: 'INTEGER'
    player_1_unit_CreepTumor: 'INTEGER'
    player_1_upgrade_BansheeCloak: 'INTEGER'
    player_1_upgrade_BansheeSpeed: 'INTEGER'
    player_1_upgrade_BattlecruiserEnableSpecializations: 'INTEGER'
    player_1_upgrade_CycloneLockOnDamageUpgrade: 'INTEGER'
    player_1_upgrade_DrillClaws: 'INTEGER'
    player_1_upgrade_HighCapacityBarrels: 'INTEGER'
    player_1_upgrade_HiSecAutoTracking: 'INTEGER'
    player_1_upgrade_LiberatorAGRangeUpgrade: 'INTEGER'
    player_1_upgrade_MedivacIncreaseSpeedBoost: 'INTEGER'
    player_1_upgrade_PersonalCloaking: 'INTEGER'
    player_1_upgrade_PunisherGrenades: 'INTEGER'
    player_1_upgrade_ShieldWall: 'INTEGER'
    player_1_upgrade_SmartServos: 'INTEGER'
    player_1_upgrade_Stimpack: 'INTEGER'
    player_1_upgrade_TerranBuildingArmor: 'INTEGER'
    player_1_upgrade_TerranInfantryArmorsLevel1: 'INTEGER'
    player_1_upgrade_TerranInfantryArmorsLevel2: 'INTEGER'
    player_1_upgrade_TerranInfantryArmorsLevel3: 'INTEGER'
    player_1_upgrade_TerranInfantryWeaponsLevel1: 'INTEGER'
    player_1_upgrade_TerranInfantryWeaponsLevel2: 'INTEGER'
    player_1_upgrade_TerranInfantryWeaponsLevel3: 'INTEGER'
    player_1_upgrade_TerranShipWeaponsLevel1: 'INTEGER'
    player_1_upgrade_TerranShipWeaponsLevel2: 'INTEGER'
    player_1_upgrade_TerranShipWeaponsLevel3: 'INTEGER'
    player_1_upgrade_TerranVehicleAndShipArmorsLevel1: 'INTEGER'
    player_1_upgrade_TerranVehicleAndShipArmorsLevel2: 'INTEGER'
    player_1_upgrade_TerranVehicleAndShipArmorsLevel3: 'INTEGER'
    player_1_upgrade_TerranVehicleWeaponsLevel1: 'INTEGER'
    player_1_upgrade_TerranVehicleWeaponsLevel2: 'INTEGER'
    player_1_upgrade_TerranVehicleWeaponsLevel3: 'INTEGER'
    player_1_unit_SCV: 'INTEGER'
    player_1_unit_MULE: 'INTEGER'
    player_1_unit_Marine: 'INTEGER'
    player_1_unit_Marauder: 'INTEGER'
    player_1_unit_Reaper: 'INTEGER'
    player_1_unit_Ghost: 'INTEGER'
    player_1_unit_Hellion: 'INTEGER'
    player_1_unit_Hellbat: 'INTEGER'
    player_1_unit_WidowMine: 'INTEGER'
    player_1_unit_SiegeTank: 'INTEGER'
    player_1_unit_Cyclone: 'INTEGER'
    player_1_unit_Thor: 'INTEGER'
    player_1_unit_Viking: 'INTEGER'
    player_1_unit_Medivac: 'INTEGER'
    player_1_unit_Liberator: 'INTEGER'
    player_1_unit_Banshee: 'INTEGER'
    player_1_unit_Raven: 'INTEGER'
    player_1_unit_Battlecruiser: 'INTEGER'
    player_1_unit_Nuke: 'INTEGER'
    player_1_unit_PlanetaryFortress: 'INTEGER'
    player_1_unit_CommandCenter: 'INTEGER'
    player_1_unit_OrbitalCommand: 'INTEGER'
    player_1_unit_SupplyDepot: 'INTEGER'
    player_1_unit_Refinery: 'INTEGER'
    player_1_unit_Barracks: 'INTEGER'
    player_1_unit_EngineeringBay: 'INTEGER'
    player_1_unit_Bunker: 'INTEGER'
    player_1_unit_MissileTurret: 'INTEGER'
    player_1_unit_SensorTower: 'INTEGER'
    player_1_unit_Factory: 'INTEGER'
    player_1_unit_GhostAcademy: 'INTEGER'
    player_1_unit_Armory: 'INTEGER'
    player_1_unit_Starport: 'INTEGER'
    player_1_unit_FusionCore: 'INTEGER'
    player_1_unit_TechLab: 'INTEGER'
    player_1_unit_Reactor: 'INTEGER'
    player_1_upgrade_AdeptPiercingAttack: 'INTEGER'
    player_1_upgrade_BlinkTech: 'INTEGER'
    player_1_upgrade_Charge: 'INTEGER'
    player_1_upgrade_DarkTemplarBlinkUpgrade: 'INTEGER'
    player_1_upgrade_ExtendedThermalLance: 'INTEGER'
    player_1_upgrade_GraviticDrive: 'INTEGER'
    player_1_upgrade_ObserverGraviticBooster: 'INTEGER'
    player_1_upgrade_PhoenixRangeUpgrade: 'INTEGER'
    player_1_upgrade_ProtossAirArmorsLevel1: 'INTEGER'
    player_1_upgrade_ProtossAirArmorsLevel2: 'INTEGER'
    player_1_upgrade_ProtossAirArmorsLevel3: 'INTEGER'
    player_1_upgrade_ProtossAirWeaponsLevel1: 'INTEGER'
    player_1_upgrade_ProtossAirWeaponsLevel2: 'INTEGER'
    player_1_upgrade_ProtossAirWeaponsLevel3: 'INTEGER'
    player_1_upgrade_ProtossGroundArmorsLevel1: 'INTEGER'
    player_1_upgrade_ProtossGroundArmorsLevel2: 'INTEGER'
    player_1_upgrade_ProtossGroundArmorsLevel3: 'INTEGER'
    player_1_upgrade_ProtossGroundWeaponsLevel1: 'INTEGER'
    player_1_upgrade_ProtossGroundWeaponsLevel2: 'INTEGER'
    player_1_upgrade_ProtossGroundWeaponsLevel3: 'INTEGER'
    player_1_upgrade_ProtossShieldsLevel1: 'INTEGER'
    player_1_upgrade_ProtossShieldsLevel2: 'INTEGER'
    player_1_upgrade_ProtossShieldsLevel3: 'INTEGER'
    player_1_upgrade_PsiStormTech: 'INTEGER'
    player_1_upgrade_TempestGroundAttackUpgrade: 'INTEGER'
    player_1_upgrade_VoidRaySpeedUpgrade: 'INTEGER'
    player_1_upgrade_WarpGateResearch: 'INTEGER'
    player_1_unit_Probe: 'INTEGER'
    player_1_unit_Zealot: 'INTEGER'
    player_1_unit_Sentry: 'INTEGER'
    player_1_unit_Stalker: 'INTEGER'
    player_1_unit_Adept: 'INTEGER'
    player_1_unit_HighTemplar: 'INTEGER'
    player_1_unit_DarkTemplar: 'INTEGER'
    player_1_unit_Archon: 'INTEGER'
    player_1_unit_Observer: 'INTEGER'
    player_1_unit_WarpPrism: 'INTEGER'
    player_1_unit_Immortal: 'INTEGER'
    player_1_unit_Colossus: 'INTEGER'
    player_1_unit_Disruptor: 'INTEGER'
    player_1_unit_Phoenix: 'INTEGER'
    player_1_unit_VoidRay: 'INTEGER'
    player_1_unit_Oracle: 'INTEGER'
    player_1_unit_Tempest: 'INTEGER'
    player_1_unit_Carrier: 'INTEGER'
    player_1_unit_Mothership: 'INTEGER'
    player_1_unit_Nexus: 'INTEGER'
    player_1_unit_Pylon: 'INTEGER'
    player_1_unit_Assimilator: 'INTEGER'
    player_1_unit_Gateway: 'INTEGER'
    player_1_unit_Forge: 'INTEGER'
    player_1_unit_PhotonCannon: 'INTEGER'
    player_1_unit_ShieldBattery: 'INTEGER'
    player_1_unit_WarpGate: 'INTEGER'
    player_1_unit_CyberneticsCore: 'INTEGER'
    player_1_unit_TwilightCouncil: 'INTEGER'
    player_1_unit_RoboticsFacility: 'INTEGER'
    player_1_unit_Stargate: 'INTEGER'
    player_1_unit_TemplarArchive: 'INTEGER'
    player_1_unit_DarkShrine: 'INTEGER'
    player_1_unit_RoboticsBay: 'INTEGER'
    player_1_unit_FleetBeacon: 'INTEGER'
    player_1_special_minerals-available: 'INTEGER'
    player_1_special_vespene-available: 'INTEGER'
    player_2_upgrade_AnabolicSynthesis: 'INTEGER'
    player_2_upgrade_Burrow: 'INTEGER'
    player_2_upgrade_CentrificalHooks: 'INTEGER'
    player_2_upgrade_ChitinousPlating: 'INTEGER'
    player_2_upgrade_DiggingClaws: 'INTEGER'
    player_2_upgrade_EvolveGroovedSpines: 'INTEGER'
    player_2_upgrade_EvolveMuscularAugments: 'INTEGER'
    player_2_upgrade_GlialReconstitution: 'INTEGER'
    player_2_upgrade_InfestorEnergyUpgrade: 'INTEGER'
    player_2_upgrade_LurkerRange: 'INTEGER'
    player_2_upgrade_NeuralParasite: 'INTEGER'
    player_2_upgrade_overlordspeed: 'INTEGER'
    player_2_upgrade_TunnelingClaws: 'INTEGER'
    player_2_upgrade_ZergFlyerArmorsLevel1: 'INTEGER'
    player_2_upgrade_ZergFlyerArmorsLevel2: 'INTEGER'
    player_2_upgrade_ZergFlyerArmorsLevel3: 'INTEGER'
    player_2_upgrade_ZergFlyerWeaponsLevel1: 'INTEGER'
    player_2_upgrade_ZergFlyerWeaponsLevel2: 'INTEGER'
    player_2_upgrade_ZergFlyerWeaponsLevel3: 'INTEGER'
    player_2_upgrade_ZergGroundArmorsLevel1: 'INTEGER'
    player_2_upgrade_ZergGroundArmorsLevel2: 'INTEGER'
    player_2_upgrade_ZergGroundArmorsLevel3: 'INTEGER'
    player_2_upgrade_zerglingattackspeed: 'INTEGER'
    player_2_upgrade_zerglingmovementspeed: 'INTEGER'
    player_2_upgrade_ZergMeleeWeaponsLevel1: 'INTEGER'
    player_2_upgrade_ZergMeleeWeaponsLevel2: 'INTEGER'
    player_2_upgrade_ZergMeleeWeaponsLevel3: 'INTEGER'
    player_2_upgrade_ZergMissileWeaponsLevel1: 'INTEGER'
    player_2_upgrade_ZergMissileWeaponsLevel2: 'INTEGER'
    player_2_upgrade_ZergMissileWeaponsLevel3: 'INTEGER'
    player_2_unit_Drone: 'INTEGER'
    player_2_unit_Queen: 'INTEGER'
    player_2_unit_Zergling: 'INTEGER'
    player_2_unit_Baneling: 'INTEGER'
    player_2_unit_Roach: 'INTEGER'
    player_2_unit_Ravager: 'INTEGER'
    player_2_unit_Hydralisk: 'INTEGER'
    player_2_unit_Lurker: 'INTEGER'
    player_2_unit_Infestor: 'INTEGER'
    player_2_unit_SwarmHost: 'INTEGER'
    player_2_unit_Ultralisk: 'INTEGER'
    player_2_unit_Overlord: 'INTEGER'
    player_2_unit_Overseer: 'INTEGER'
    player_2_unit_Mutalisk: 'INTEGER'
    player_2_unit_Corruptor: 'INTEGER'
    player_2_unit_Viper: 'INTEGER'
    player_2_unit_BroodLord: 'INTEGER'
    player_2_unit_Hatchery: 'INTEGER'
    player_2_unit_Extractor: 'INTEGER'
    player_2_unit_SpawningPool: 'INTEGER'
    player_2_unit_EvolutionChamber: 'INTEGER'
    player_2_unit_SpineCrawler: 'INTEGER'
    player_2_unit_SporeCrawler: 'INTEGER'
    player_2_unit_RoachWarren: 'INTEGER'
    player_2_unit_BanelingNest: 'INTEGER'
    player_2_unit_Lair: 'INTEGER'
    player_2_unit_HydraliskDen: 'INTEGER'
    player_2_unit_LurkerDen: 'INTEGER'
    player_2_unit_InfestationPit: 'INTEGER'
    player_2_unit_Spire: 'INTEGER'
    player_2_unit_NydusNetwork: 'INTEGER'
    player_2_unit_Hive: 'INTEGER'
    player_2_unit_UltraliskCavern: 'INTEGER'
    player_2_unit_GreaterSpire: 'INTEGER'
    player_2_unit_CreepTumor: 'INTEGER'
    player_2_upgrade_BansheeCloak: 'INTEGER'
    player_2_upgrade_BansheeSpeed: 'INTEGER'
    player_2_upgrade_BattlecruiserEnableSpecializations: 'INTEGER'
    player_2_upgrade_CycloneLockOnDamageUpgrade: 'INTEGER'
    player_2_upgrade_DrillClaws: 'INTEGER'
    player_2_upgrade_HighCapacityBarrels: 'INTEGER'
    player_2_upgrade_HiSecAutoTracking: 'INTEGER'
    player_2_upgrade_LiberatorAGRangeUpgrade: 'INTEGER'
    player_2_upgrade_MedivacIncreaseSpeedBoost: 'INTEGER'
    player_2_upgrade_PersonalCloaking: 'INTEGER'
    player_2_upgrade_PunisherGrenades: 'INTEGER'
    player_2_upgrade_ShieldWall: 'INTEGER'
    player_2_upgrade_SmartServos: 'INTEGER'
    player_2_upgrade_Stimpack: 'INTEGER'
    player_2_upgrade_TerranBuildingArmor: 'INTEGER'
    player_2_upgrade_TerranInfantryArmorsLevel1: 'INTEGER'
    player_2_upgrade_TerranInfantryArmorsLevel2: 'INTEGER'
    player_2_upgrade_TerranInfantryArmorsLevel3: 'INTEGER'
    player_2_upgrade_TerranInfantryWeaponsLevel1: 'INTEGER'
    player_2_upgrade_TerranInfantryWeaponsLevel2: 'INTEGER'
    player_2_upgrade_TerranInfantryWeaponsLevel3: 'INTEGER'
    player_2_upgrade_TerranShipWeaponsLevel1: 'INTEGER'
    player_2_upgrade_TerranShipWeaponsLevel2: 'INTEGER'
    player_2_upgrade_TerranShipWeaponsLevel3: 'INTEGER'
    player_2_upgrade_TerranVehicleAndShipArmorsLevel1: 'INTEGER'
    player_2_upgrade_TerranVehicleAndShipArmorsLevel2: 'INTEGER'
    player_2_upgrade_TerranVehicleAndShipArmorsLevel3: 'INTEGER'
    player_2_upgrade_TerranVehicleWeaponsLevel1: 'INTEGER'
    player_2_upgrade_TerranVehicleWeaponsLevel2: 'INTEGER'
    player_2_upgrade_TerranVehicleWeaponsLevel3: 'INTEGER'
    player_2_unit_SCV: 'INTEGER'
    player_2_unit_MULE: 'INTEGER'
    player_2_unit_Marine: 'INTEGER'
    player_2_unit_Marauder: 'INTEGER'
    player_2_unit_Reaper: 'INTEGER'
    player_2_unit_Ghost: 'INTEGER'
    player_2_unit_Hellion: 'INTEGER'
    player_2_unit_Hellbat: 'INTEGER'
    player_2_unit_WidowMine: 'INTEGER'
    player_2_unit_SiegeTank: 'INTEGER'
    player_2_unit_Cyclone: 'INTEGER'
    player_2_unit_Thor: 'INTEGER'
    player_2_unit_Viking: 'INTEGER'
    player_2_unit_Medivac: 'INTEGER'
    player_2_unit_Liberator: 'INTEGER'
    player_2_unit_Banshee: 'INTEGER'
    player_2_unit_Raven: 'INTEGER'
    player_2_unit_Battlecruiser: 'INTEGER'
    player_2_unit_Nuke: 'INTEGER'
    player_2_unit_PlanetaryFortress: 'INTEGER'
    player_2_unit_CommandCenter: 'INTEGER'
    player_2_unit_OrbitalCommand: 'INTEGER'
    player_2_unit_SupplyDepot: 'INTEGER'
    player_2_unit_Refinery: 'INTEGER'
    player_2_unit_Barracks: 'INTEGER'
    player_2_unit_EngineeringBay: 'INTEGER'
    player_2_unit_Bunker: 'INTEGER'
    player_2_unit_MissileTurret: 'INTEGER'
    player_2_unit_SensorTower: 'INTEGER'
    player_2_unit_Factory: 'INTEGER'
    player_2_unit_GhostAcademy: 'INTEGER'
    player_2_unit_Armory: 'INTEGER'
    player_2_unit_Starport: 'INTEGER'
    player_2_unit_FusionCore: 'INTEGER'
    player_2_unit_TechLab: 'INTEGER'
    player_2_unit_Reactor: 'INTEGER'
    player_2_upgrade_AdeptPiercingAttack: 'INTEGER'
    player_2_upgrade_BlinkTech: 'INTEGER'
    player_2_upgrade_Charge: 'INTEGER'
    player_2_upgrade_DarkTemplarBlinkUpgrade: 'INTEGER'
    player_2_upgrade_ExtendedThermalLance: 'INTEGER'
    player_2_upgrade_GraviticDrive: 'INTEGER'
    player_2_upgrade_ObserverGraviticBooster: 'INTEGER'
    player_2_upgrade_PhoenixRangeUpgrade: 'INTEGER'
    player_2_upgrade_ProtossAirArmorsLevel1: 'INTEGER'
    player_2_upgrade_ProtossAirArmorsLevel2: 'INTEGER'
    player_2_upgrade_ProtossAirArmorsLevel3: 'INTEGER'
    player_2_upgrade_ProtossAirWeaponsLevel1: 'INTEGER'
    player_2_upgrade_ProtossAirWeaponsLevel2: 'INTEGER'
    player_2_upgrade_ProtossAirWeaponsLevel3: 'INTEGER'
    player_2_upgrade_ProtossGroundArmorsLevel1: 'INTEGER'
    player_2_upgrade_ProtossGroundArmorsLevel2: 'INTEGER'
    player_2_upgrade_ProtossGroundArmorsLevel3: 'INTEGER'
    player_2_upgrade_ProtossGroundWeaponsLevel1: 'INTEGER'
    player_2_upgrade_ProtossGroundWeaponsLevel2: 'INTEGER'
    player_2_upgrade_ProtossGroundWeaponsLevel3: 'INTEGER'
    player_2_upgrade_ProtossShieldsLevel1: 'INTEGER'
    player_2_upgrade_ProtossShieldsLevel2: 'INTEGER'
    player_2_upgrade_ProtossShieldsLevel3: 'INTEGER'
    player_2_upgrade_PsiStormTech: 'INTEGER'
    player_2_upgrade_TempestGroundAttackUpgrade: 'INTEGER'
    player_2_upgrade_VoidRaySpeedUpgrade: 'INTEGER'
    player_2_upgrade_WarpGateResearch: 'INTEGER'
    player_2_unit_Probe: 'INTEGER'
    player_2_unit_Zealot: 'INTEGER'
    player_2_unit_Sentry: 'INTEGER'
    player_2_unit_Stalker: 'INTEGER'
    player_2_unit_Adept: 'INTEGER'
    player_2_unit_HighTemplar: 'INTEGER'
    player_2_unit_DarkTemplar: 'INTEGER'
    player_2_unit_Archon: 'INTEGER'
    player_2_unit_Observer: 'INTEGER'
    player_2_unit_WarpPrism: 'INTEGER'
    player_2_unit_Immortal: 'INTEGER'
    player_2_unit_Colossus: 'INTEGER'
    player_2_unit_Disruptor: 'INTEGER'
    player_2_unit_Phoenix: 'INTEGER'
    player_2_unit_VoidRay: 'INTEGER'
    player_2_unit_Oracle: 'INTEGER'
    player_2_unit_Tempest: 'INTEGER'
    player_2_unit_Carrier: 'INTEGER'
    player_2_unit_Mothership: 'INTEGER'
    player_2_unit_Nexus: 'INTEGER'
    player_2_unit_Pylon: 'INTEGER'
    player_2_unit_Assimilator: 'INTEGER'
    player_2_unit_Gateway: 'INTEGER'
    player_2_unit_Forge: 'INTEGER'
    player_2_unit_PhotonCannon: 'INTEGER'
    player_2_unit_ShieldBattery: 'INTEGER'
    player_2_unit_WarpGate: 'INTEGER'
    player_2_unit_CyberneticsCore: 'INTEGER'
    player_2_unit_TwilightCouncil: 'INTEGER'
    player_2_unit_RoboticsFacility: 'INTEGER'
    player_2_unit_Stargate: 'INTEGER'
    player_2_unit_TemplarArchive: 'INTEGER'
    player_2_unit_DarkShrine: 'INTEGER'
    player_2_unit_RoboticsBay: 'INTEGER'
    player_2_unit_FleetBeacon: 'INTEGER'
    player_2_special_minerals-available: 'INTEGER'
    player_2_special_vespene-available: 'INTEGER'
  creation_closure: 
    row0: "PRIMARY KEY (tick, game_id)"
    row1: "FOREIGN KEY (game_id) REFERENCES game_info"

