game_info:
  table_name: "game_info"
  create_table_file: "./queries/create_game_info.sql"
  insert_file: "./queries/insert_game_info.sql"
  insert_get_id_file: "./queries/insert_get_id_game_info.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"
  select_game_id_file: "./queries/select_id_game_info.sql"
  select_file: "./queries/select_all.sql"
  select_player: "./queries/select_player_game_info.sql"
  update_path_file: "./queries/update_path_game_info.sql"
    
player_info:  
  table_name: "player_info"
  create_table_file: "./queries/create_player_info.sql"
  insert_file: "./queries/insert_player_info.sql"
  update_file: "./queries/update_player_info.sql"
  preinsert_select_file: "./queries/preinsert_select_player_info.sql"
  select_file: "./queries/select_all.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

map_info:
  table_name: "map_info"
  create_table_file: "./queries/create_map_info.sql"
  insert_file: "./queries/insert_map_info.sql"
  update_file: "./queries/update_map_info.sql"
  preinsert_select_file: "./queries/preinsert_select_map_info.sql"
  select_file: "./queries/select_all.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

build_order:
  table_name: "build_order"
  create_table_file: "./queries/create_build_order.sql"
  get_columns_file: "./queries/get_columns.sql"
  insert_file: "./queries/insert_build_order.sql"
  select_file: "./queries/select_all.sql"
  select_by_keys: "./queries/select_by_keys_build_order.sql"
  get_tables_file: "./queries/get_tables.sql"
  drop_table_file: "./queries/drop_table.sql"

matchup_table:
  table_name: "matchup_table"
  create_table_file: "./queries/create_table_matchup.sql"
  get_columns_file: "./queries/get_columns.sql"
  get_tables_file: "./queries/get_tables.sql"
  insert_file: "./queries/insert_data_matchup.sql"
  select_file: "./queries/select_all.sql"
  select_where_key: "./queries/select_by_key_matchup.sql"
  select_where_id: "./queries/select_where_id.sql"
  drop_table_file: "./queries/drop_table.sql"
